<?php

declare(strict_types=1);

namespace App\Services;

class OpenRouterService
{
    public static function generateQuizzes(string $topic, int $numQuestions = 3, string $customApiKey = ''): array
    {
        $config = require dirname(__DIR__, 2) . '/config/openrouter.php';
        $apiKey = !empty($customApiKey) ? trim($customApiKey) : $config['api_key'];

        if (empty($apiKey)) {
            throw new \InvalidArgumentException('OpenRouter API Key is missing. Please configure it or enter it in the form.');
        }

        $systemPrompt = <<<PROMPT
You are an expert educational quiz generator for a Chinese language learning platform (DaoHanTang).
Generate exactly {$numQuestions} multiple-choice quiz questions for the following topic/lesson content:

Topic/Context: "{$topic}"

CRITICAL REQUIREMENTS:
1. Each question must have 4 options: option_a, option_b, option_c, option_d.
2. Provide correct_option as a single lowercase letter: 'a', 'b', 'c', or 'd'.
3. Include Pinyin and English translations where appropriate for Chinese learning.
4. Output MUST be ONLY valid JSON matching this exact array structure, with NO markdown code blocks, NO ```json wrapping, and NO additional text before or after:

[
  {
    "question": "Question text here?",
    "option_a": "Option A text",
    "option_b": "Option B text",
    "option_c": "Option C text",
    "option_d": "Option D text",
    "correct_option": "a"
  }
]
PROMPT;

        $payload = [
            'model' => $config['model'],
            'messages' => [
                ['role' => 'system', 'content' => 'You are a helpful educational AI assistant that outputs raw JSON only.'],
                ['role' => 'user', 'content' => $systemPrompt],
            ],
            'temperature' => 0.7,
        ];

        $ch = curl_init($config['url']);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_POST           => true,
            CURLOPT_POSTFIELDS     => json_encode($payload),
            CURLOPT_HTTPHEADER     => [
                'Content-Type: application/json',
                'Authorization: Bearer ' . $apiKey,
                'HTTP-Referer: http://localhost/daohantang',
                'X-Title: DaoHanTang Chinese Platform',
            ],
            CURLOPT_TIMEOUT        => 30,
        ]);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlError = curl_error($ch);
        curl_close($ch);

        if ($response === false || !empty($curlError)) {
            throw new \RuntimeException('Network error connecting to OpenRouter API: ' . $curlError);
        }

        if ($httpCode !== 200) {
            $errJson = json_decode($response, true);
            $errMsg = $errJson['error']['message'] ?? "HTTP Status {$httpCode}";
            throw new \RuntimeException('OpenRouter API Error: ' . $errMsg);
        }

        $responseData = json_decode($response, true);
        $content = $responseData['choices'][0]['message']['content'] ?? '';

        if (empty($content)) {
            throw new \RuntimeException('Empty response received from OpenRouter AI.');
        }

        // Clean up markdown code blocks if present
        $cleanContent = trim($content);
        $cleanContent = preg_replace('/^```(?:json)?\s*/i', '', $cleanContent);
        $cleanContent = preg_replace('/\s*```$/', '', $cleanContent);
        $cleanContent = trim($cleanContent);

        $quizzes = json_decode($cleanContent, true);

        if (!is_array($quizzes)) {
            throw new \RuntimeException('Failed to parse AI generated JSON quiz format: ' . substr($cleanContent, 0, 150));
        }

        // Validate and normalize fields
        $validated = [];
        foreach ($quizzes as $item) {
            if (empty($item['question'])) {
                continue;
            }

            $correct = strtolower(trim((string) ($item['correct_option'] ?? 'a')));
            if (!in_array($correct, ['a', 'b', 'c', 'd'], true)) {
                $correct = 'a';
            }

            $validated[] = [
                'question'       => trim((string) $item['question']),
                'option_a'       => trim((string) ($item['option_a'] ?? '')),
                'option_b'       => trim((string) ($item['option_b'] ?? '')),
                'option_c'       => trim((string) ($item['option_c'] ?? '')),
                'option_d'       => trim((string) ($item['option_d'] ?? '')),
                'correct_option' => $correct,
            ];
        }

        if (empty($validated)) {
            throw new \RuntimeException('No valid questions generated by AI.');
        }

        return $validated;
    }
}
